### ISSUE TITLE
questions about the GPS  coordinates

### ISSUE THREAD

**Issue by vision-zhao** [JingqingZ/BaiduTraffic#11]
I feel a little confused about the GPS coordinates provided in the file 'link_gps'.
I've tried to plot the location of road in the google map, but there existed some offset. Where the ploted points in always seems not like a road. So I'm wondering:
1 what coordinate system are they in?WGS84?GCJ-02?or BD-09 of Baidu?
2 are the gps coordinates given in the dataset  aiming at the true road in reality? how can I get the specific road for a pair of gps coordinate?or it need to be kept serect?

Thank you in advance

**Comment by bbliao** [comment]
@vision-zhao 
1. The gps information of the link is extracted from some_name.mif provided by Baidu. The file is started with:
`Version 300
Charset "WindowsSimpChinese"
Delimiter "	"
CoordSys Earth Projection 1,0
...`
2. Actually, there is another file contains the name of the link. Unfortunately, we can not provide the file for security.
Thanks for your attention!
