### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by xyf1995** [JingqingZ/BaiduTraffic#13]
Hello, I looked at readme.md, and I find that it did not say how to run this code? How do you write its running command? 
     python train.py?
Thank you!

**Comment by JingqingZ** [comment]
Hi, you may train the models by entering the `src` folder and running
```
python train.py
```
Note that
* You may need to specify which model(s) to train by commenting and uncommenting line 1682-1772 in `train.py`
* Please make sure that the data has been downloaded and properly preprocessed. 
* Please make sure that the dependencies mentioned in section `Code` in `readme.md` have been installed.

**Comment by xyf1995** [comment]
Thank you for your reply!

**Comment by xyf1995** [comment]
I am a beginner, when looking at this code there are several questions: 
1、The intermediate file is to be generated through the code itself? I downloaded these 9 files but still can't find some files in the code, it feels like there are a lot of folder paths in the code, but I can't find 
such as:   path="../query_beijing_parsed_filtered", root_dir = "../../Baidu/pkl/"
2、road network sub-dataset、query sub-dataset and so on the GitHub. Where are these 3 files used?
Thank you!

**Comment by JingqingZ** [comment]
1. You may need to modify the `path` and `root_dir` in the code according to your local directory structure.
2. The original three data subsets are used to generate the intermediate files.

I am not sure if these answered your questions.

Thanks!
