### ISSUE TITLE
Could not find GPS of node?

### ISSUE THREAD

**Issue by eathen-zheng** [JingqingZ/BaiduTraffic#14]
Hi, I have downloaded the dataset, and confront with the similar problem with the closed issue #6.
I have mapped snode_id, enode_id to 13 digits new link_id. However they are not contained in the link_gps file.

So how can I get the GPS of these node_id?

**Comment by bbliao** [comment]
Hi, @eathen-zheng Please refer to closed issue [#5.](https://github.com/JingqingZ/BaiduTraffic/issues/5)
Thanks for your attention! 

> uncompress the road_network_sub-dataset.zip, you will find two files: road_network_sub-dataset and link_gps. The link_gps file contains the gps of the node. Like this:
1802838360064	116.367557	39.899537
1004419350530	116.378945	39.958013
1144134225924	116.412118	39.988885
1802838360069	116.267194	39.837811
