### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by prateikarora** [JingqingZ/BaiduTraffic#15]
The links at the Baidu Webpage are not working. Unable to download.

**Comment by JingqingZ** [comment]
There seems something wrong with the platform.

Please try the links below 
https://dataset-bj.cdn.bcebos.com/sked/query_sub-dataset.zip
https://dataset-bj.cdn.bcebos.com/sked/traffic_speed_sub-dataset.zip
https://dataset-bj.cdn.bcebos.com/sked/road_network_sub-dataset.zip

Alternatively,
https://pan.baidu.com/s/1t4p8kDlZAvrYZHnz5vHaBA

**Comment by prateikarora** [comment]
thank you very much
