### ISSUE TITLE
Question regarding baseline models

### ISSUE THREAD

**Issue by prateikarora** [JingqingZ/BaiduTraffic#17]
In the baseline models that you implemented(specifically RF and SVR); were they trained solely on the temporal data or the entire spatio-temporal data?

**Comment by JingqingZ** [comment]
Hi, the baselines (RF and SVR) were trained and tested on traffic speed data only, which means we used (v_1, v_2, ... v_t) to predict (v_{t+1}, ...). For your reference, the implementation of baselines can be found at [line43 src/baselines.py](https://github.com/JingqingZ/BaiduTraffic/blob/a04ae23ba5f3508fccc04f4a76416c8e101a63ba/src/baselines.py#L43)
