### ISSUE TITLE
如何获取交通流量数据集

### ISSUE THREAD

**Issue by caoh18** [JingqingZ/BaiduTraffic#19]
您好，
     我看到这里做了一个交通数据集的对比，主要有的是道路速度的数据，请问有没有道路流量的数据呢，如果没有的话有没有其他公开数据集提供道路流量数据呢，感谢！

**Comment by JingqingZ** [comment]
您好！
很抱歉我们的数据集中并没有道路流量的数据，您可以一方面参考我们提供的数据集对比表格，查看其他数据集是否提供流量数据，另外据我所知如下公开数据集提供有流量数据：

https://data.gov.uk/dataset/9562c512-4a0b-45ee-b6ad-afc0f99b841f/highways-england-network-journey-time-and-traffic-flow-data

谢谢
