### ISSUE TITLE
Some useful intermediate-file do not find

### ISSUE THREAD

**Issue by RobinLu1209** [JingqingZ/BaiduTraffic#24]
Hi! I find many data loaded in [WideDeep_Controller] can not be found...

```
coarse_file = open(config.data_path + "wide_features/event_link_set_all_poi_type_feature_coarse_beijing_1km.pkl", "rb")
    fine_file = open(config.data_path + "wide_features/event_link_set_all_poi_type_feature_fine_beijing_1km.pkl", "rb")
    info_file = open(config.data_path + "wide_features/event_link_set_all_beijing_1km_link_info_feature.pkl", "rb")
    time_file = open(config.data_path + "wide_features/time_feature_15min.pkl", "rb")
```

So how can I get these files, thank you!

**Comment by JingqingZ** [comment]
Hi, thanks for you message!

Please find if [data/wide_feature_readme.md](https://github.com/JingqingZ/BaiduTraffic/blob/wide-feature-extraction/data/wide_feature_readme.md) and [code](https://github.com/JingqingZ/BaiduTraffic/tree/wide-feature-extraction/src) in the [wide-feature-extraction](https://github.com/JingqingZ/BaiduTraffic/tree/wide-feature-extraction/) branch may help you. 

All the intermediate files we can provide are already attached [here](https://github.com/JingqingZ/BaiduTraffic/blob/master/intermediate_files/readme.md) where there is a BaiduPan link. We are sorry for any inconvenience.

Thanks!
