### ISSUE TITLE
link_gps中无snode与enode的坐标信息

### ISSUE THREAD

**Issue by RobinLu1209** [JingqingZ/BaiduTraffic#25]
大神，你好！我今天在使用数据的时候惊奇的发现，road_network_sub-dataset.v2数据中的snodeid与enodeid的经纬度坐标信息在link_gps中是不存在的...请问是什么原因？谢谢！

**Comment by JingqingZ** [comment]
Hi, you would probably find [issue#16](https://github.com/JingqingZ/BaiduTraffic/issues/16) useful. In the meanwhile, @bbliao could you help take this question?

**Comment by bbliao** [comment]
@RobinLu1209 As @JingqingZ said, you may find issue #16 useful.

**Comment by RobinLu1209** [comment]
你好，我看了issue#16，不过似乎并没有解答我的问题，以及目前我又遇到了一系列问题，略显繁琐，不过希望可以得到回答，谢谢~
1.     issue#16等问题中提到的snode与enode的id是hash-id，不过似乎已经被修正，但是修正后的id依旧不正确，我怀疑是hash算法有错，导致依旧无法查询到snode和enode的经纬度等信息。例如，第一条数据的snode id是1520445066，但这个id是无法在link_gps中搜到的。
2.     你们提供的经纬度信息是gps的经纬度还是百度地图的经纬度呢？两个经纬度数值是不一样的，我将你们提供的经纬度转换成百度地图使用的坐标发现不少数据点并不在道路上，可能是产生了漂移，甚至大量数据在楼宇中，不知你们是否知情？以及你们当初是如何设计的？
3.     我利用osmnx等工具包去分析数据的时候发现，你们的道路划分非常细，最短距离为2米，最长不到500米，这些道路划分你们是怎么做的，谢谢。

**Comment by RobinLu1209** [comment]
你好，我看了issue#16，不过似乎并没有解答我的问题，以及目前我又遇到了一系列问题，略显繁琐，不过希望可以得到回答，谢谢~
1. issue#16等问题中提到的snode与enode的id是hash-id，不过似乎已经被修正，但是修正后的id依旧不正确，我怀疑是hash算法有错，导致依旧无法查询到snode和enode的经纬度等信息。例如，第一条数据的snode id是1520445066，但这个id是无法在link_gps中搜到的。
2. 你们提供的经纬度信息是gps的经纬度还是百度地图的经纬度呢？两个经纬度数值是不一样的，我将你们提供的经纬度转换成百度地图使用的坐标发现不少数据点并不在道路上，可能是产生了漂移，甚至大量数据在楼宇中，不知你们是否知情？以及你们当初是如何设计的？
3. 我利用osmnx等工具包去分析数据的时候发现，你们的道路划分非常细，最短距离为2米，最长不到500米，这些道路划分你们是怎么做的，谢谢。

**Comment by bbliao** [comment]
@RobinLu1209 
1. As issue #16 said, due to the privacy and data completeness, we can **not** provide the gps information of each node；
2. The original gps coordinates are Baidu Mercator coordinates, and we convert it to gps coordinates with [mercator_convertor.py](https://github.com/JingqingZ/BaiduTraffic/blob/master/intermediate_files/mercator_convertor.py);
3. The link information is provided by Baidu Map, and we do not pay much attention to how they are created.

**Comment by RobinLu1209** [comment]
[Why there is no any snode and enode road network information : (](https://github.com/RobinLu1209/STGCN/blob/master/beijing_traffic/figure/baidu_data.PNG)

**Comment by RobinLu1209** [comment]
I have upload a screenshot of my code, and I want to achieve the road information of snode and enode(link width, length, lanenum, etc.) but none of them are included. I know there may be some data security, but I do not think it should be nothing....

**Comment by RobinLu1209** [comment]
[当我查看neighbour_1km这个数据的时候，惊奇的发现，某一条路的snode和enode居然不在pagerank的前十名](https://github.com/RobinLu1209/STGCN/blob/master/beijing_traffic/figure/baidu_data_2.PNG)

我相信这不是一个巧合......希望可以给出一个解释，谢谢~

**Comment by bbliao** [comment]
> I have upload a screenshot of my code, and I want to achieve the road information of snode and enode(link width, length, lanenum, etc.) but none of them are included. I know there may be some data security, but I do not think it should be nothing....

@RobinLu1209 On the one hand, due to data privacy, we can not provide the road network information of all the snodes and enodes; on the other hand, even though we provided, we could not ensure the data completeness (traffic speed) of them (all the snodes and enodes).

**Comment by bbliao** [comment]
> [当我查看neighbour_1km这个数据的时候，惊奇的发现，某一条路的snode和enode居然不在pagerank的前十名](https://github.com/RobinLu1209/STGCN/blob/master/beijing_traffic/figure/baidu_data_2.PNG)
> 
> 我相信这不是一个巧合......希望可以给出一个解释，谢谢~

On one hand, we just use the PageRank algorithm to select the top 10 important links from the neighthours, we did not assume all the snode and enode are in the top 10 neighbours. On the other hand, due to data completeness, the links may be removed from the top 10 neighbours if the traffic speed data missing rate of the link are larger than 1%.

**Comment by RobinLu1209** [comment]
Okay. Although I don't think this is a satisfactory answer for me, and it will bring a lot of obstacles to my personal research work. Thank you for your answers to my questions all the time, although for many reasons, each answer may make me sigh.
I choose to close this issue, but I sincerely hope to get in touch with you personally. Maybe we can have a better exchange of this data on another platform.
