### ISSUE TITLE
Hi! Where can I download ur paper?

### ISSUE THREAD

**Issue by ChenNed** [JingqingZ/BaiduTraffic#3]

**Comment by JingqingZ** [comment]
Hi, 
Thanks for your interest in our paper. As SIGKDD hasn't published the paper, we cannot provide an official download link for it. But you may find the latest version below which is also the version we recently submitted to the SIGKDD committee.

[sigkdd-2018-traffic.pdf](https://github.com/JingqingZ/BaiduTraffic/files/2098112/sigkdd-2018-traffic.pdf)
