### ISSUE TITLE
Traffic Speed Sub-dataset Damaged

### ISSUE THREAD

**Issue by ChengZY** [JingqingZ/BaiduTraffic#4]
Hi, I have download Q-Traffic Dataset in the link 
https://ai.baidu.com/broad/introduction?dataset=traffic 
But I can't unzip the file, The file Traffic Speed Sub-dataset, as the file is damaged. How can I access to the dataset?

**Comment by bbliao** [comment]
@ChengZY Sorry for the damaged dataset, we will re-upload the dataset soon. You can download the dataset at https://pan.baidu.com/s/1t4p8kDlZAvrYZHnz5vHaBA. But the download speed of this link might be a little slow.
