### ISSUE TITLE
No node GPS in Road Network Sub-dataset

### ISSUE THREAD

**Issue by ChengZY** [JingqingZ/BaiduTraffic#5]
Hi, I have downloaded the dataset. In the road_network_sub-dataset, I can not see the snodegps and enodegps mentioned in ReadMe, or any other files which can map the node id with the corresponding gps. 
Could you upload this part?

**Comment by bbliao** [comment]
Hello, ChengZY, uncompress the road_network_sub-dataset.zip, you will find two files: road_network_sub-dataset and link_gps. The link_gps file contains the gps of the node. Like this:
1802838360064	116.367557	39.899537
1004419350530	116.378945	39.958013
1144134225924	116.412118	39.988885
1802838360069	116.267194	39.837811

**Comment by ChengZY** [comment]
@bbliao In the road_network_sub-dataset there are link_id and node_id, and the link_id in link_gps file can match to the link_id in road_network_sub-dataset file . Or the link_id in link_gps should match to the nodes id in road_network_sub-dataset file?

**Comment by bbliao** [comment]
@ChengZY Yes, the gps of the link_id, snode_id, and enode_id are all in the link_gps file since they are all link.
