### ISSUE TITLE
为什么对query使用LSTM？

### ISSUE THREAD

**Issue by brness** [JingqingZ/BaiduTraffic#9]
query的问题直观上没有时序关系，为什么会想到用LSTM来处理query呢？

**Comment by JingqingZ** [comment]
每一个搜索query的信息都包含出发时间和预计抵达时间，所以query本身是跟时序相关的

**Comment by brness** [comment]
谢谢您的答复。还有一个问题就是模型融合的时候要考虑一些什么呢？就比如说为什么将Attribute放置decoder的FC层以及Graph CNN为什么在encoder的输入层？

**Comment by JingqingZ** [comment]
在我们的模型当中融合辅助信息主要考虑：
- Attribute的融合主要参考[Wide and Deep Leanring](https://ai.googleblog.com/2016/06/wide-deep-learning-better-together-with.html)
- Graph CNN的作用是将附近节点的traffic speed融合进模型当中，因为与`{v_1,...,v_t}`同为traffic speed，所以用同一个encoder融合最为直接
- Query Impact (QI)的信息相对独立，所以另外用了一个encoder进行融合

**Comment by brness** [comment]
非常感谢您的答复！！have a good day!

**Comment by JingqingZ** [comment]
感谢您的关注！～
